import spacy
from spacy.lang.es import Spanish
from spacy.pipeline import EntityRuler
from spacy_lookup import Entity

nlp = spacy.load('es_core_news_sm')
ruler = EntityRuler(nlp)

patterns = [{"label": "frailes", "pattern": "frailes"},
        {"label": "santiago londoño", "pattern": [{"lower": "santiago"}, {"lower": "londoño"}]},
        {"label": "camilo mejia", "pattern": [{"lower": "camilo"}, {"lower": "mejía"}]},
        {"label": "naranjales", "pattern": "naranjales"},
        {"label": "los rosales", "pattern": [{"lower": "los"}, {"lower": "rosales"}]},
        {"label": "las violetas", "pattern": [{"lower": "las"}, {"lower": "violetas"}]},        
        {"label": "los lagos", "pattern": [{"lower": "los"}, {"lower": "lagos"}]},
        {"label": "la pradera", "pattern": [{"lower": "la"}, {"lower": "pradera"}]},
        {"label": "carrera 21", "pattern": [{"lower": "carrera"}, {"lower": "21"}]},
        {"label": "av santa monica", "pattern": [{"lower": "avenida"}, {"lower": "santa"},{"lower":"monica"}]},
        {"label": "av santa monica", "pattern": [{"lower": "avenida"}, {"lower": "santa"},{"lower":"mónica"}]},
        {"label": "carrera 19 a", "pattern": [{"lower": "carrera"}, {"lower": "19"},{"lower": "a"}]},
        {"label": "carrera 19 a", "pattern": [{"lower": "carrera"}, {"lower": "19a"}]},
        {"label": "calle 12", "pattern": [{"lower": "calle"}, {"lower": "12"}]},
        {"label": "calle 13", "pattern": [{"lower": "calle"}, {"lower": "13"}]},
        {"label": "carrera 17", "pattern": [{"lower": "carrera"}, {"lower": "17"}]},
        {"label": "calle 8", "pattern": [{"lower": "calle"}, {"lower": "8"}]},
        {"label": "la popa", "pattern": [{"lower": "la"}, {"lower": "popa"}]},
        {"label": "la popa", "pattern": "popa"},
        {"label": "interseccion viaducto", "pattern": "viaducto"},
        {"label": "puente mosquera", "pattern": [{"lower": "puente"}, {"lower": "mosquera"}]},
        {"label": "av del rio", "pattern": [{"lower": "avenida"}, {"lower": "del"},{"lower": "rio"}]},
        {"label": "av del rio", "pattern": [{"lower": "avenida"}, {"lower": "del"},{"lower": "río"}]},
        {"label": "inteseccion turín", "pattern": "turín"},
        {"label": "inteseccion turín", "pattern": [{"lower": "intersección"}, {"lower": "turín"}]},
        {"label": "av 30 de agosto", "pattern": [{"lower": "avenida"}, {"lower": "30"},{"lower": "de"},{"lower":"agosto"}]},
        {"label": "av 30 de agosto", "pattern": [{"lower": "Avenida"}, {"lower": "30"},{"lower": "de"},{"lower":"agosto"}]},
        {"label": "calle 50", "pattern": [{"lower": "calle"}, {"lower": "50"}]},
        {"label": "maraya", "pattern": "maraya"},
        {"label": "inem", "pattern": "inem"}, #TODO volver a cargar la base de datos
        {"label": "parte baja jardin 1", "pattern": [{"lower": "parte"}, {"lower": "baja"},{"lower": "jardín"},{"lower": "1"}]},
        {"label": "parte baja jardín 1", "pattern": [{"lower": "jardin"}, {"lower": "1"}]},
        {"label": "av. las americas", "pattern": [{"lower": "avenida"}, {"lower": "las"},{"lower": "americas"}]},
        {"label": "av. las americas", "pattern": [{"lower": "avenida"}, {"lower": "las"},{"lower": "américas"}]},
        {"label": "home center", "pattern": [{"lower": "home"}, {"lower": "center"}]},
        {"label": "home center", "pattern": "homecenter"},
        {"label": "av. las americas", "pattern": [{"lower": "avenida"}, {"lower": "de"},{"lower": "las"},{"lower": "americas"}]},
        {"label": "av. las americas", "pattern": [{"lower": "avenida"}, {"lower": "de"},{"lower": "las"},{"lower": "américas"}]},
        {"label": "av. el dorado", "pattern": [{"lower": "avenida"}, {"lower": "el"},{"lower": "dorado"}]},
        {"label": "panorama", "pattern": [{"lower": "panorama"}, {"lower": "2"}]},
        {"label": "antonio jose valencia", "pattern": [{"lower": "antonio"}, {"lower": "josé"},{"lower": "valencia"}]},
        {"label": "bella sardi", "pattern": [{"lower": "bella"}, {"lower": "sardi"}]},
        {"label": "naranjito", "pattern": "naranjito"},
        {"label": "altos de las mercedes", "pattern": [{"lower": "altos"}, {"lower": "de"},{"lower": "las"},{"lower": "mercedes"}]},
        {"label": "altos de las mercedes", "pattern": [{"lower": "las"}, {"lower": "mercedes"}]},
        {"label": "los cristales", "pattern": [{"lower": "los"}, {"lower": "cristales"}]},
        {"label": "2500 lotes", "pattern": [{"lower": "2500"}, {"lower": "lotes"}]},
        {"label": "2500 lotes", "pattern": [{"lower": "2.500"}, {"lower": "lotes"}]},
        {"label": "calle 75", "pattern": [{"lower": "calle"}, {"lower": "75"}]},
        {"label": "calle 75", "pattern": [{"lower": "calle"}, {"lower": "75a"}]},
        {"label": "carrera", "pattern": [{"lower": "carrera"}, {"lower": "44"}]},
        {"label": "calle 76", "pattern": [{"lower": "calle"}, {"lower": "76"}]},
        {"label": "carrera 43", "pattern": [{"lower": "carrera"}, {"lower": "43"}]},
        {"label": "alejandria", "pattern": "alejandría"},
        {"label": "navarra", "pattern": "navarra"},
        {"label": "montelibano", "pattern": "montelibano"},
        {"label": "montelibano", "pattern": [{"lower": "monte"}, {"lower": "líbano"}]},
        {"label": "avda. valher", "pattern": [{"lower": "avenida"}, {"lower": "valer"}]},
        {"label": "avda. valher", "pattern": [{"lower": "avenida"}, {"lower": "baler"}]},
        {"label": "santa mónica", "pattern": [{"lower": "santa"}, {"lower": "mónica"}]},
        {"label": "carrera 44", "pattern": [{"lower": "carrera"}, {"lower": "44"}]},
        {"label": "remanso", "pattern": "remanso"},
        {"label": "tokio", "pattern": "tokio"},
        {"label": "brisas", "pattern": [{"lower": "brisas"}, {"lower": "brisas"}]},
        {"label": "danubio", "pattern": "danubio"},
        {"label": "intermedio", "pattern": "intermedio"},
        {"label": "calle 18 bis este", "pattern": [{"lower": "calle"}, {"lower": "18"},{"lower": "bis"}]},
        {"label": "calle 18 bis este", "pattern": [{"lower": "calle"}, {"lower": "18"},{"lower": "bis"},{"lower": "este"}]},
        {"label": "carrera 23", "pattern": [{"lower": "carrera"}, {"lower": "23"}]},
        {"label": "el otoño", "pattern": [{"lower": "el"}, {"lower": "otoño"}]},
        {"label": "las margaritas", "pattern": [{"lower": "las"}, {"lower": "margaritas"}]},
        {"label": "monserrate", "pattern": "monserrate"},
        {"label": "el pizamo", "pattern": [{"lower": "el"}, {"lower": "pizamo"}]},
        {"label": "avda. santander", "pattern": [{"lower": "avenida"}, {"lower": "santander"}]},
        {"label": "cra 11", "pattern": [{"lower": "carrera"}, {"lower": "11"}]},
        {"label": "calle 4", "pattern": [{"lower": "calle"}, {"lower": "4"}]},
        {"label": "cra 12", "pattern": [{"lower": "carrera"}, {"lower": "12"}]},
        {"label": "la rebeca", "pattern": [{"lower": "la"}, {"lower": "rebeca"}]},
        {"label": "avda. circunvalar", "pattern": [{"lower": "avenida"}, {"lower": "circunvalar"}]},
        {"label": "avda. circunvalar", "pattern": "circunvalar"},
        {"label": "calle 14", "pattern": [{"lower": "calle"}, {"lower": "14"}]},
        {"label": "carrera 5a", "pattern": [{"lower": "carrera"}, {"lower": "5"},{"lower": "a"}]},
        {"label": "carrera 5a", "pattern": [{"lower": "carrera"}, {"lower": "quinta"}]},
        {"label": "calle 10", "pattern": [{"lower": "calle"}, {"lower": "10"}]},
        {"label": "carrera 4a", "pattern": [{"lower": "carrera"}, {"lower": "cuarta"}]},
        {"label": "carrera 4a", "pattern": [{"lower": "carrera"}, {"lower": "cuatro"},{"lower": "a"}]},
        {"label": "la macarena", "pattern": [{"lower": "la"}, {"lower": "macarena"}]},
        {"label": "postobon", "pattern": "postobon"},
        {"label": "diagonal 26", "pattern": [{"lower": "diagonal"}, {"lower": "26"}]},
        {"label": "diagonal 25 a", "pattern": [{"lower": "diagonal"}, {"lower": "25"},{"lower": "a"}]},
        {"label": "santa isabel transversal 7", "pattern": [{"lower": "santa"}, {"lower": "isabel"},{"lower": "transversal"},{"lower": "7"}]},
        {"label": "santa isabel transversal 7", "pattern": [{"lower": "santa"}, {"lower": "isabel"},{"lower": "transversal"}]},
        {"label": "carrera 7", "pattern": [{"lower": "carrera"}, {"lower": "7"}]},
        {"label": "calle 32", "pattern": [{"lower": "calle"}, {"lower": "32"}]},
        {"label": "av. ferrocarril", "pattern": [{"lower": "avenida"}, {"lower": "ferrocarril"}]},
        {"label": "glorieta postobón", "pattern": [{"lower": "glorieta"}, {"lower": "postobón"}]},
        {"label": "avda. ferrocarril hacia el norte de dosquebradas", "pattern": [{"lower": "avenida"}, {"lower": "ferrocarril"},{"lower": "hacia"},{"lower": "norte"},{"lower": "de"},{"lower": "dosquebradas"}]},
        {"label": "playa rica", "pattern": [{"lower": "playa"}, {"lower": "rica"}]},
        {"label": "diagonal 27 a", "pattern": [{"lower": "diagonal"}, {"lower": "27"},{"lower": "a"}]},
        {"label": "transversal", "pattern": [{"lower": "transversal"}, {"lower": "8"}]},
        {"label": "calle 3", "pattern": [{"lower": "calle"}, {"lower": "3"}]},
        {"label": "cra 10", "pattern": [{"lower": "carrera"}, {"lower": "10"}]},
        {"label": "kennedy", "pattern": "kennedy"},
        {"label": "kennedy", "pattern": "kenedi"},
        {"label": "kennedy", "pattern": "kenedy"},
        {"label": "variante romelia el pollo", "pattern": "pollo"},
        {"label": "variante romelia el pollo", "pattern": [{"lower": "el"}, {"lower": "pollo"}]},
        {"label": "variante romelia el pollo", "pattern": [{"lower": "via"}, {"lower": "el"},{"lower": "pollo"}]},
        {"label": "variante romelia el pollo", "pattern": [{"lower": "variante"}, {"lower": "romelia"}]},
        {"label": "variante romelia el pollo", "pattern": [{"lower": "variante"}, {"lower": "el"}, {"lower": "pollo"} ]},
        {"label": "variante romelia el pollo", "pattern": [{"lower": "variante"}, {"lower": "romelia"}, {"lower": "el"}, {"lower":"pollo"}]},
        {"label": "guaduales", "pattern": "guaduales"},
        {"label": "campestre c", "pattern": [{"lower": "campestre"}, {"lower": "c"}]},
        {"label": "campestre b", "pattern": [{"lower": "campestre"}, {"lower": "b"}]},
        {"label": "limonar", "pattern": "limonar"},
        {"label": "carrera 4", "pattern": [{"lower": "carrera"}, {"lower": "4"}]},
        {"label": "calle 27", "pattern": [{"lower": "calle"}, {"lower": "27"}]},
        {"label": "avda. belalcazar", "pattern": [{"lower": "avenida"}, {"lower": "belalcazar"}]},
        {"label": "terminal de transportes", "pattern": "terminal"},
        {"label": "terminal de transportes", "pattern": [{"lower": "la"}, {"lower": "terminal"}]},
        {"label": "terminal de transportes", "pattern": [{"lower": "el"}, {"lower": "terminal"}]},
        {"label": "los cedros", "pattern": [{"lower": "los"}, {"lower": "cedros"}]},
        {"label": "barrio la playa", "pattern": [{"lower": "barrio"}, {"lower": "la"},{"lower": "playa"}]},
        {"label": "puente gamma", "pattern": [{"lower": "puente"}, {"lower": "gamma"}]},
        {"label": "puente gamma", "pattern": [{"lower": "puente"}, {"lower": "gama"}]},
        {"label": "barrio alfa", "pattern": [{"lower": "barrio"}, {"lower": "alfa"}]},
        {"label": "barrio gamma", "pattern": [{"lower": "barrio"}, {"lower": "gamma"}]},
        {"label": "barrio gamma", "pattern": [{"lower": "barrio"}, {"lower": "gama"}]},
        {"label": "los corales", "pattern": [{"lower": "los"}, {"lower": "corales"}]},
        {"label": "glorieta variante condina", "pattern": [{"lower": "glorieta"}, {"lower": "variante"},{"lower": "condina"}]},
        {"label": "glorieta variante condina", "pattern": [{"lower": "variante"},{"lower": "condina"}]},
        {"label": "urbanizacion salamanca", "pattern": [{"lower": "urbanización"}, {"lower": "salamanca"}]},
        {"label": "nuevo sol", "pattern": [{"lower": "nuevo"}, {"lower": "sol"}]},
        {"label": "san marcos", "pattern": [{"lower": "san"}, {"lower": "marcos"}]},
        {"label": "san joaquin", "pattern": [{"lower": "san"}, {"lower": "joaquín"}]},
        {"label": "glorieta corales", "pattern": [{"lower": "glorieta"}, {"lower": "corales"}]},
        {"label": "calle 81", "pattern": [{"lower": "calle"}, {"lower": "81"}]},
        {"label": "carrera 25", "pattern": [{"lower": "carrera"}, {"lower": "25"}]},
        {"label": "barrio san fernando", "pattern": [{"lower": "san"}, {"lower": "fernando"}]},
        {"label": "la dulcera", "pattern": [{"lower": "la"}, {"lower": "dulcera"}]},
        {"label": "vuelta al centro comercial la 14", "pattern": [{"lower": "la"}, {"lower": "14"}]},
        {"label": "vuelta al centro comercial la 14", "pattern": [{"lower": "centro"}, {"lower": "comercial"},{"lower": "la"},{"lower": "14"}]},
        {"label": "calle 17", "pattern": [{"lower": "calle"}, {"lower": "17"}]},
        {"label": "invico", "pattern": "invico"},
        {"label": "luis", "pattern": "luis"},
        {"label": "luis", "pattern": [{"lower": "san"}, {"lower": "luis"}]},
        {"label": "victoria", "pattern": "victoria"},
        {"label": "montelibano", "pattern": "montelibano"},
        {"label": "nicolas", "pattern": "nicolás"},
        {"label": "nicolas", "pattern": "nicolas"},
        {"label": "utp", "pattern": "utp"},
        {"label": "utp", "pattern": "tecnologica"},
        {"label": "dosquebradas", "pattern": "dosquebradas"}]

ruler.add_patterns(patterns)
nlp.add_pipe(ruler)

#doc = nlp(u"rutas que me lleven de san luis a pollo")
def clasification(texto):
    puntos = []
    doc = nlp(texto)
    for ent in doc.ents:
        puntos.append(ent.label_)
    return puntos
